// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    CitySelector: typeof import('./src/components/CitySelector.vue')['default']
    FoodCard: typeof import('./src/components/FoodCard.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InfoCard: typeof import('./src/components/InfoCard.vue')['default']
    RegionCard: typeof import('./src/components/RegionCard.vue')['default']
    Tag: typeof import('./src/components/Tag.vue')['default']
  }
}

export { }
